name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-linux:
    name: Linux (amd64)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build .

  build-macos:
    name: macOS (arm64)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - run: brew install cmake
      - run: make
      - run: shards build --error-trace demo
